### ISSUE TITLE
Postinstall fails on AWS instances

### ISSUE THREAD

**Issue by Yserz** [runk/node-geolite2#13]
It seems to be not permitted to create folder on AWS instances.

```
> geolite2@2.0.0 postinstall /tmp/deployment/application/node_modules/geolite2
> scripts/postinstall

+ mkdir -p dbs
mkdir: cannot create directory ‘dbs’: Permission denied

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geolite2@2.0.0 postinstall: `scripts/postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the geolite2@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by runk** [comment]
Yup, it's on my radar and being addressed. For now - stick to v1.x

**Comment by runk** [comment]
v2.0.2 fixed this issue

**Comment by Yserz** [comment]
Unfortunately the issue still persist. Here's the error:
```
> geolite2@2.0.2 postinstall /tmp/deployment/application/node_modules/geolite2
> node scripts/postinstall.js

fs.js:114
throw err;
^

Error: EACCES: permission denied, mkdir '/tmp/deployment/application/node_modules/geolite2/dbs'
at Object.mkdirSync (fs.js:752:3)
at Object.<anonymous> (/tmp/deployment/application/node_modules/geolite2/scripts/postinstall.js:15:38)
at Module._compile (internal/modules/cjs/loader.js:701:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
at Module.load (internal/modules/cjs/loader.js:600:32)
at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
at Function.Module._load (internal/modules/cjs/loader.js:531:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
at startup (internal/bootstrap/node.js:283:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by runk** [comment]
Issue is different though. Can you troubleshoot it please? Is parent directory there? What are the permissions?
